# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: out.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tout.proto\x12\x0fgoogle.protobuf\"\xb2\x02\n\rImageResponse\x12\x10\n\x06img_id\x18\x01 \x02(\t:\x00\x12\x32\n\x05\x66\x61\x63\x65s\x18\x02 \x03(\x0b\x32#.google.protobuf.ImageResponse.Face\x12:\n\x08insights\x18\x03 \x03(\x0b\x32(.google.protobuf.ImageResponse.Embedding\x12:\n\x08\x66\x61\x63\x65nets\x18\x04 \x03(\x0b\x32(.google.protobuf.ImageResponse.Embedding\x1a\x32\n\x04\x46\x61\x63\x65\x12\t\n\x01x\x18\x01 \x02(\x05\x12\t\n\x01y\x18\x02 \x02(\x05\x12\t\n\x01w\x18\x03 \x02(\x05\x12\t\n\x01h\x18\x04 \x02(\x05\x1a/\n\tEmbedding\x12\x15\n\x04type\x18\x01 \x02(\t:\x07insight\x12\x0b\n\x03\x65mb\x18\x02 \x03(\x01')



_IMAGERESPONSE = DESCRIPTOR.message_types_by_name['ImageResponse']
_IMAGERESPONSE_FACE = _IMAGERESPONSE.nested_types_by_name['Face']
_IMAGERESPONSE_EMBEDDING = _IMAGERESPONSE.nested_types_by_name['Embedding']
ImageResponse = _reflection.GeneratedProtocolMessageType('ImageResponse', (_message.Message,), {

  'Face' : _reflection.GeneratedProtocolMessageType('Face', (_message.Message,), {
    'DESCRIPTOR' : _IMAGERESPONSE_FACE,
    '__module__' : 'out_pb2'
    # @@protoc_insertion_point(class_scope:google.protobuf.ImageResponse.Face)
    })
  ,

  'Embedding' : _reflection.GeneratedProtocolMessageType('Embedding', (_message.Message,), {
    'DESCRIPTOR' : _IMAGERESPONSE_EMBEDDING,
    '__module__' : 'out_pb2'
    # @@protoc_insertion_point(class_scope:google.protobuf.ImageResponse.Embedding)
    })
  ,
  'DESCRIPTOR' : _IMAGERESPONSE,
  '__module__' : 'out_pb2'
  # @@protoc_insertion_point(class_scope:google.protobuf.ImageResponse)
  })
_sym_db.RegisterMessage(ImageResponse)
_sym_db.RegisterMessage(ImageResponse.Face)
_sym_db.RegisterMessage(ImageResponse.Embedding)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGERESPONSE._serialized_start=31
  _IMAGERESPONSE._serialized_end=337
  _IMAGERESPONSE_FACE._serialized_start=238
  _IMAGERESPONSE_FACE._serialized_end=288
  _IMAGERESPONSE_EMBEDDING._serialized_start=290
  _IMAGERESPONSE_EMBEDDING._serialized_end=337
# @@protoc_insertion_point(module_scope)
